base_model: google/gemma-2-27b-it
hub_model_id: your-hugging-face-username/gemma-2-27b-it-dolly-15k

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: databricks/databricks-dolly-15k
    type:
      field_instruction: instruction       
      field_input: context
      field_output: response
val_set_size: 0.05

sequence_len: 2048
sample_packing: true
eval_sample_packing: false
pad_to_sequence_len: true

adapter: qlora
lora_model_dir:
lora_r: 32
lora_alpha: 64
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 4
num_epochs: 1
optimizer: adamw_torch
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: true

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: false

warmup_steps: 10
evals_per_epoch: 4
saves_per_epoch: 1
weight_decay: 0.0
debug:
deepspeed: deepspeed_configs/zero2.json
fsdp:
fsdp_config:
special_tokens:
output_dir:
dataset_prepared_path:
